name: flutter_switcher_example
description: Demonstrates how to use the flutter_switcher plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_switch:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/images/
